version: '3'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha18
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
    command:
      - graphql-engine
      - serve
      - --enable-console
  dodo-frontend:
    build: dodo-frontend
    volumes:
      - /dodo-frontend/node_modules
      - /dodo-frontend/tmp
      - ./dodo-frontend:/dodo-frontend
    ports:
      - '3000:3000'
volumes:
  db_data:
